### ISSUE TITLE
cloned repository location on remote computer

### ISSUE THREAD

**Issue by jkuzhila** [dopanic/team1c#3]
I cloned the team1c repository for trial to my computer. Where can I open that repository on my computer before to add/commit/push changes ? a Random question

**Comment by jonpardev** [comment]
Recall what you did for the previous assignments. 1) Make a folder in your computer 2) Set the folder as local git working space 3) Set Github and push from the local git to Github. Right? Only 3) is changed. Not push, just pull from the Github.
